### ISSUE TITLE
Allow content from different editions

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/big-ft#68] opened 2016-02-12 17:36 UTC
Currently, Big FT content reflects the content of the UK version of the FT, which isn't necessarily what customers/offices in other climates/continents/timezones want. If we created a way to select the international or region-specific versions, we broaden Big FTs appeal

**Comment by AdaRoseCannon** [comment] 2016-02-23 02:11
Closed by #74

**Closed as completed by AdaRoseCannon** 2016-02-23 02:11 UTC
Labels: duplicate

**Comment by AdaRoseCannon** [comment] 2016-02-23 02:15
Duplicate of #65

**Comment by AdaRoseEdwards** [comment] 2016-02-23 02:16
Duplicate of #65
